// Code generated by protoc-gen-go. DO NOT EDIT.
// Run `make proto` to regenerate from api/proto/node_agent.proto
//
// This stub satisfies the compiler until the real generated code is in place.

package proto

import (
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

// ── Requests & Responses ──────────────────────────────────────────────────

type RegisterNodeRequest struct {
	Hostname            string
	Address             string
	Region              string
	Country             string
	AgentVersion        string
	SupportedTransports []string
}

type RegisterNodeResponse struct {
	NodeId  string
	Success bool
	Message string
}

type HeartbeatRequest struct {
	NodeId          string
	CpuUsage        float64
	MemUsage        float64
	BandwidthIn     int64
	BandwidthOut    int64
	ActiveConns     int32
	AgentVersion    string
	TransportHealth []*TransportHealth
}

type TransportHealth struct {
	Transport string
	Status    string
	LatencyMs int64
}

type HeartbeatResponse struct {
	ConfigChanged bool
	Message       string
}

type GetConfigRequest struct {
	NodeId string
}

type GetConfigResponse struct {
	Configs []*TransportConfig
}

type TransportConfig struct {
	TransportType string
	Port          int32
	ConfigJson    []byte
	Enabled       bool
}

type MetricsEvent struct {
	NodeId      string
	Ts          *timestamppb.Timestamp
	BytesIn     int64
	BytesOut    int64
	ActiveConns int32
	Transport   string
}

type MetricsAck struct {
	Received bool
}
