// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// Run `make proto` to regenerate from api/proto/node_agent.proto

package proto

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// NodeAgentServiceClient is the client API for NodeAgentService.
type NodeAgentServiceClient interface {
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	ReportMetrics(ctx context.Context, opts ...grpc.CallOption) (NodeAgentService_ReportMetricsClient, error)
}

type nodeAgentServiceClient struct{ cc grpc.ClientConnInterface }

func NewNodeAgentServiceClient(cc grpc.ClientConnInterface) NodeAgentServiceClient {
	return &nodeAgentServiceClient{cc}
}

func (c *nodeAgentServiceClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, "/vpnplatform.agent.v1.NodeAgentService/RegisterNode", in, out, opts...)
	return out, err
}

func (c *nodeAgentServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, "/vpnplatform.agent.v1.NodeAgentService/Heartbeat", in, out, opts...)
	return out, err
}

func (c *nodeAgentServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, "/vpnplatform.agent.v1.NodeAgentService/GetConfig", in, out, opts...)
	return out, err
}

func (c *nodeAgentServiceClient) ReportMetrics(ctx context.Context, opts ...grpc.CallOption) (NodeAgentService_ReportMetricsClient, error) {
	stream, err := c.cc.NewStream(ctx, &NodeAgentService_ServiceDesc.Streams[0], "/vpnplatform.agent.v1.NodeAgentService/ReportMetrics", opts...)
	if err != nil {
		return nil, err
	}
	return &nodeAgentServiceReportMetricsClient{stream}, nil
}

type NodeAgentService_ReportMetricsClient interface {
	Send(*MetricsEvent) error
	CloseAndRecv() (*MetricsAck, error)
	grpc.ClientStream
}

type nodeAgentServiceReportMetricsClient struct{ grpc.ClientStream }

func (x *nodeAgentServiceReportMetricsClient) Send(m *MetricsEvent) error {
	return x.ClientStream.SendMsg(m)
}

func (x *nodeAgentServiceReportMetricsClient) CloseAndRecv() (*MetricsAck, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(MetricsAck)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NodeAgentServiceServer is the server API for NodeAgentService.
type NodeAgentServiceServer interface {
	RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	ReportMetrics(NodeAgentService_ReportMetricsServer) error
	mustEmbedUnimplementedNodeAgentServiceServer()
}

// UnimplementedNodeAgentServiceServer must be embedded for forward compatibility.
type UnimplementedNodeAgentServiceServer struct{}

func (UnimplementedNodeAgentServiceServer) RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedNodeAgentServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedNodeAgentServiceServer) GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedNodeAgentServiceServer) ReportMetrics(NodeAgentService_ReportMetricsServer) error {
	return status.Errorf(codes.Unimplemented, "method ReportMetrics not implemented")
}
func (UnimplementedNodeAgentServiceServer) mustEmbedUnimplementedNodeAgentServiceServer() {}

type NodeAgentService_ReportMetricsServer interface {
	SendAndClose(*MetricsAck) error
	Recv() (*MetricsEvent, error)
	grpc.ServerStream
}

type nodeAgentServiceReportMetricsServer struct{ grpc.ServerStream }

func (x *nodeAgentServiceReportMetricsServer) SendAndClose(m *MetricsAck) error {
	return x.ServerStream.SendMsg(m)
}

func (x *nodeAgentServiceReportMetricsServer) Recv() (*MetricsEvent, error) {
	m := new(MetricsEvent)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func RegisterNodeAgentServiceServer(s grpc.ServiceRegistrar, srv NodeAgentServiceServer) {
	s.RegisterService(&NodeAgentService_ServiceDesc, srv)
}

var NodeAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vpnplatform.agent.v1.NodeAgentService",
	HandlerType: (*NodeAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _NodeAgentService_RegisterNode_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _NodeAgentService_Heartbeat_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _NodeAgentService_GetConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportMetrics",
			Handler:       _NodeAgentService_ReportMetrics_Handler,
			ClientStreams: true,
		},
	},
}

func _NodeAgentService_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/vpnplatform.agent.v1.NodeAgentService/RegisterNode"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/vpnplatform.agent.v1.NodeAgentService/Heartbeat"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/vpnplatform.agent.v1.NodeAgentService/GetConfig"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_ReportMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeAgentServiceServer).ReportMetrics(&nodeAgentServiceReportMetricsServer{stream})
}
