#!/usr/bin/env bash
# deploy-control-plane.sh — Install the VPN control plane + web portal on a fresh Ubuntu 22.04 VPS.
#
# Usage (run as root on the target server):
#   curl -sSL https://raw.githubusercontent.com/slgao/oracle-vpn/main/scripts/deploy-control-plane.sh | \
#     DOMAIN=vpn.yourdomain.com \
#     EMAIL=you@example.com \
#     GITHUB_REPO=https://github.com/slgao/oracle-vpn \
#     bash
#
# Or copy and run interactively:
#   scp scripts/deploy-control-plane.sh root@YOUR_CP_SERVER:/tmp/
#   ssh root@YOUR_CP_SERVER
#   DOMAIN=vpn.yourdomain.com EMAIL=you@example.com bash /tmp/deploy-control-plane.sh

set -euo pipefail

DOMAIN="${DOMAIN:-}"
EMAIL="${EMAIL:-}"
GITHUB_REPO="${GITHUB_REPO:-https://github.com/slgao/oracle-vpn}"
APP_DIR="${APP_DIR:-/opt/vpnplatform}"
DB_PASSWORD="${DB_PASSWORD:-$(openssl rand -hex 16)}"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; RED='\033[0;31m'; BOLD='\033[1m'; NC='\033[0m'
info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
die()     { echo -e "${RED}[FAIL]${NC}  $*" >&2; exit 1; }

[[ $(id -u) -eq 0 ]] || die "Run as root"
[[ -n "$DOMAIN" ]]   || die "Set DOMAIN=vpn.yourdomain.com"
[[ -n "$EMAIL" ]]    || die "Set EMAIL=you@example.com"

echo ""
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}   VPN Platform — Control Plane Deployment${NC}"
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
info "Domain:     $DOMAIN"
info "Email:      $EMAIL"
info "Repo:       $GITHUB_REPO"
info "App dir:    $APP_DIR"
echo ""

# ── 1. System deps ────────────────────────────────────────────────────────────
info "Installing system packages..."
apt-get update -qq
apt-get install -y -qq curl git ufw nginx certbot python3-certbot-nginx

# ── 2. Docker ─────────────────────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
  info "Installing Docker..."
  curl -fsSL https://get.docker.com | sh
  systemctl enable --now docker
  success "Docker installed"
else
  success "Docker already installed"
fi

# ── 3. Clone / update repo ────────────────────────────────────────────────────
if [[ -d "$APP_DIR/.git" ]]; then
  info "Updating existing repo in $APP_DIR..."
  git -C "$APP_DIR" pull --ff-only
else
  info "Cloning $GITHUB_REPO → $APP_DIR..."
  git clone "$GITHUB_REPO" "$APP_DIR"
fi
success "Repo ready at $APP_DIR"

# ── 4. Write .env ─────────────────────────────────────────────────────────────
JWT_SECRET=$(openssl rand -hex 32)
REFRESH_SECRET=$(openssl rand -hex 32)

cat > "$APP_DIR/.env" <<EOF
# Generated by deploy-control-plane.sh — $(date -u)
POSTGRES_USER=vpnplatform
POSTGRES_PASSWORD=$DB_PASSWORD
POSTGRES_DB=vpnplatform

DATABASE_URL=postgres://vpnplatform:$DB_PASSWORD@postgres:5432/vpnplatform?sslmode=disable
REDIS_URL=redis://redis:6379

JWT_SECRET=$JWT_SECRET
JWT_REFRESH_SECRET=$REFRESH_SECRET
JWT_ACCESS_TTL=15m
JWT_REFRESH_TTL=7d

API_PORT=8080
GRPC_PORT=9090
METRICS_PORT=9092

LOG_LEVEL=info
EOF
chmod 600 "$APP_DIR/.env"
success ".env written"

# ── 5. UFW firewall ───────────────────────────────────────────────────────────
info "Configuring firewall..."
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh
ufw allow 80/tcp   # HTTP (for ACME challenge)
ufw allow 443/tcp  # HTTPS (portal + API)
ufw --force enable
success "Firewall: ports 22, 80, 443 open"

# ── 6. nginx — initial config (no TLS yet) ────────────────────────────────────
info "Writing nginx config..."
cat > "/etc/nginx/sites-available/vpnplatform" <<EOF
server {
    listen 80;
    server_name $DOMAIN;

    # Certbot ACME challenge
    location /.well-known/acme-challenge/ { root /var/www/html; }

    # API proxy
    location /api/ {
        proxy_pass         http://127.0.0.1:8080;
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_read_timeout 30s;
    }

    # gRPC (node agents connect here)
    location /grpc/ {
        grpc_pass          grpc://127.0.0.1:9090;
    }

    # Web portal
    location / {
        proxy_pass http://127.0.0.1:1420;
        proxy_set_header Host \$host;
    }
}
EOF
ln -sf /etc/nginx/sites-available/vpnplatform /etc/nginx/sites-enabled/vpnplatform
rm -f /etc/nginx/sites-enabled/default
nginx -t && systemctl reload nginx
success "nginx configured"

# ── 7. Start control plane ────────────────────────────────────────────────────
info "Starting control plane stack..."
cd "$APP_DIR"
docker compose pull --quiet 2>/dev/null || true
docker compose up -d --remove-orphans
sleep 5

# Verify API is up
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8080/healthz || echo "000")
if [[ "$HTTP_CODE" == "200" ]]; then
  success "Control plane API is healthy"
else
  warn "API health check returned HTTP $HTTP_CODE — check: docker compose logs control-plane"
fi

# ── 8. TLS via Let's Encrypt ──────────────────────────────────────────────────
info "Obtaining TLS certificate for $DOMAIN..."
certbot --nginx \
  --non-interactive \
  --agree-tos \
  --email "$EMAIL" \
  --domains "$DOMAIN" \
  --redirect
success "TLS certificate installed"

# Reload nginx with TLS config
systemctl reload nginx

# Auto-renew
systemctl enable --now certbot.timer 2>/dev/null || \
  (crontab -l 2>/dev/null; echo "0 3 * * * certbot renew --quiet && systemctl reload nginx") | crontab -

# ── 9. Summary ────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}${BOLD}  CONTROL PLANE DEPLOYED${NC}"
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  ${BOLD}Web portal:${NC}     https://$DOMAIN"
echo -e "  ${BOLD}API base:${NC}       https://$DOMAIN/api/v1"
echo -e "  ${BOLD}Grafana:${NC}        http://$(hostname -I | awk '{print $1}'):3001  (admin/admin)"
echo -e "  ${BOLD}App directory:${NC}  $APP_DIR"
echo -e "  ${BOLD}Secrets file:${NC}   $APP_DIR/.env"
echo ""
echo -e "  ${YELLOW}Next steps:${NC}"
echo -e "  1. Register an account at https://$DOMAIN"
echo -e "  2. Promote it to admin:"
echo -e "     docker exec vpn-postgres-1 psql -U vpnplatform -d vpnplatform \\"
echo -e "       -c \"UPDATE users SET role='admin' WHERE email='you@example.com';\""
echo -e "  3. Add VPN servers:"
echo -e "     CONTROL_PLANE=https://$DOMAIN ADMIN_TOKEN=<jwt> bash scripts/setup-server.sh"
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
